# Generated by Django 5.2 on 2025-06-10 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_alter_review_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book_detail',
        ),
        migrations.DeleteModel(
            name='Add2',
        ),
    ]
