# Generated by Django 5.1.6 on 2025-03-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_category_language_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='language',
            name='lname',
            field=models.CharField(max_length=200),
        ),
    ]
