# Generated by Django 5.1.6 on 2025-04-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_alter_category_cname_alter_language_lname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
