# Generated by Django 5.2 on 2025-06-10 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_remove_review_book_detail_delete_add2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField()),
                ('description', models.TextField()),
                ('publishdate', models.DateField(auto_now_add=True)),
                ('edition', models.IntegerField()),
                ('publisher', models.TextField()),
                ('pages', models.IntegerField()),
                ('isbn', models.IntegerField()),
                ('binding', models.TextField()),
                ('stock', models.TextField(default='in stock')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='APP.add')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='book_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detailed_reviews', to='APP.add2'),
        ),
    ]
