# Generated by Django 5.2 on 2025-06-10 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_add2_review_book_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detailed_reviews', to='APP.add2'),
        ),
    ]
