# Generated by Django 5.2 on 2025-06-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0010_order_quantity_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
