# Generated by Django 5.2 on 2025-06-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0012_alter_add2_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='add2',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
